### PR TITLE
feat(tags): Allow tags to be configured

### PR DESCRIPTION
**Pull request by SpainTrain**
- New option `tags` to define logdna host tags

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 211 at r1](https://beta.reviewable.io/reviews/logdna/python/18#-LAKXzIn3p33-o63IfFi:-LAKXzIn3p33-o63IfFj:by9u76e) ([raw file](https://github.com/logdna/python/blob/6adc21e872fa521be1aaf08309f7f3d0ba3dc5c5/README.md#L211)):*
> ```Markdown
> 
> * _Optional_
> * Type: `String[]`
> ```

BTW also happy to document this as `List<String>`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/logdna/python/18)*

**Comment by SpainTrain** [comment]
:heart:

**Comment by respectus** [comment]
Thanks for the rapid updates! Your new changes should be on pypi logdna version 1.2.7

**Comment by SpainTrain** [comment]
Thanks for the rapid reviews/merges/releases :grin:

**Pull request merged**
